apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
        - pods
        - nvidia.com/gpu
      flavors:
        - name: default-flavor
          resources:
            - name: cpu
              nominalQuota: '32'
            - name: memory
              nominalQuota: 120Gi
            - name: pods
              nominalQuota: '20'
            - name: nvidia.com/gpu
              nominalQuota: '4'
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  annotations:
    kueue.x-k8s.io/default-queue: 'true'
  name: local-queue-default
spec:
  clusterQueue: cluster-queue
