apiVersion: ray.io/v1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: '1.0'
    kueue.x-k8s.io/queue-name: local-queue-default
  name: raycluster-gpu
  namespace: training
spec:
  autoscalerOptions:
    idleTimeoutSeconds: 60
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    upscalingMode: Default
  enableInTreeAutoscaling: false
  headGroupSpec:
    enableIngress: false
    rayStartParams:
      block: 'true'
      dashboard-host: 0.0.0.0
      num-gpus: '1'
    serviceType: ClusterIP
    template:
      spec:
        containers:
        - image: docker.io/rayproject/ray:2.23.0-py39-cu121
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: ray-head
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          resources:
            limits:
              cpu: 2
              memory: 35G
              nvidia.com/gpu: 1
            requests:
              cpu: 2
              memory: 35G
              nvidia.com/gpu: 1
          volumeMounts:
          - mountPath: /etc/pki/tls/certs/odh-trusted-ca-bundle.crt
            name: odh-trusted-ca-cert
            subPath: odh-trusted-ca-bundle.crt
          - mountPath: /etc/ssl/certs/odh-trusted-ca-bundle.crt
            name: odh-trusted-ca-cert
            subPath: odh-trusted-ca-bundle.crt
          - mountPath: /etc/pki/tls/certs/odh-ca-bundle.crt
            name: odh-ca-cert
            subPath: odh-ca-bundle.crt
          - mountPath: /etc/ssl/certs/odh-ca-bundle.crt
            name: odh-ca-cert
            subPath: odh-ca-bundle.crt
        imagePullSecrets: []
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        volumes:
        - configMap:
            items:
            - key: ca-bundle.crt
              path: odh-trusted-ca-bundle.crt
            name: odh-trusted-ca-bundle
            optional: true
          name: odh-trusted-ca-cert
        - configMap:
            items:
            - key: odh-ca-bundle.crt
              path: odh-ca-bundle.crt
            name: odh-trusted-ca-bundle
            optional: true
          name: odh-ca-cert
  rayVersion: 2.7.0
  workerGroupSpecs:
  - groupName: small-group-raycluster-gpu
    maxReplicas: 2
    minReplicas: 2
    rayStartParams:
      block: 'true'
      num-gpus: '1'
    replicas: 2
    template:
      metadata:
        annotations:
          key: value
        labels:
          key: value
      spec:
        containers:
        - image: docker.io/rayproject/ray:2.23.0-py39-cu121
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: machine-learning
          resources:
            limits:
              cpu: 14
              memory: 56G
              nvidia.com/gpu: 1
            requests:
              cpu: 8
              memory: 32G
              nvidia.com/gpu: 1
          volumeMounts:
          - mountPath: /etc/pki/tls/certs/odh-trusted-ca-bundle.crt
            name: odh-trusted-ca-cert
            subPath: odh-trusted-ca-bundle.crt
          - mountPath: /etc/ssl/certs/odh-trusted-ca-bundle.crt
            name: odh-trusted-ca-cert
            subPath: odh-trusted-ca-bundle.crt
          - mountPath: /etc/pki/tls/certs/odh-ca-bundle.crt
            name: odh-ca-cert
            subPath: odh-ca-bundle.crt
          - mountPath: /etc/ssl/certs/odh-ca-bundle.crt
            name: odh-ca-cert
            subPath: odh-ca-bundle.crt
        imagePullSecrets: []
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        volumes:
        - configMap:
            items:
            - key: ca-bundle.crt
              path: odh-trusted-ca-bundle.crt
            name: odh-trusted-ca-bundle
            optional: true
          name: odh-trusted-ca-cert
        - configMap:
            items:
            - key: odh-ca-bundle.crt
              path: odh-ca-bundle.crt
            name: odh-trusted-ca-bundle
            optional: true
          name: odh-ca-cert
